export const PROJECTS = [
  {
    id: 1,
    title: "intuit-risks",
    description: "intuit-risks",
    technologies: ["Vue.js", "Laravel", "API"],
    category: "fullstack",
    image: "/intuit.png",
    link: "https://github.com/pablo-crotti/intuit-risks",
    buttonText: "repo",
  },
  {
    id: 2,
    title: "ubutruc",
    description: "ubutruc",
    technologies: ["HTML", "CSS", "PHP", "JavaScript", "MySQL"],
    category: "fullstack",
    image: "/ubutruc.png",
    link: "https://iviou.ch/pdf/AttestationCollaboration.pdf",
    buttonText: "certificate",
  },
  {
    id: 3,
    title: "osteo",
    description: "ubutruc",
    technologies: ["Illustrator"],
    category: "design",
    image: "/osteo.png",
  },
  {
    id: 4,
    title: "co2",
    description: "co2",
    technologies: ["D3.js", "HTML", "CSS", "JavaScript"],
    category: "fullstack",
    image: "/co2.png",
    link: "https://github.com/nicomeuwly/CO2-Centuries",
    buttonText: "repo",
  },
  {
    id: 5,
    title: "weather",
    description: "weather",
    technologies: ["HTML", "CSS", "JavaScript", "API"],
    category: "design",
    image: "/weather.png",
    link: "https://github.com/pablo-crotti/weather-mood",
    buttonText: "repo",
  },
  {
    id: 6,
    title: "bglovers",
    description: "bglovers",
    technologies: ["Wordpress", "WooComerce", "Divi"],
    category: "design",
    image: "/bglovers.png",
    link: "https://iviou.ch/pdf/bglovers.pdf",
    buttonText: "repo",
  },
  {
    id: 7,
    title: "pronum",
    description: "pronum",
    technologies: ["Wordpress", "Elementor"],
    category: "design",
    image: "/pronum.png",
    link: "https://iviou.ch/pdf/pronum.pdf",
    buttonText: "report",
  },
  {
    id: 8,
    title: "fs",
    description: "fs",
    technologies: ["JavaScript", "A-Frame", "WebVR"],
    category: "dev",
    image: "/fs.png",
    link: "https://github.com/pablo-crotti/forest-shooter",
    buttonText: "repo",
  },
  {
    id: 9,
    title: "otw",
    description: "otw",
    technologies: ["Next.js", "API", "Tailwind CSS"],
    category: "fullstack",
    link: "https://github.com/pablo-crotti/on-the-way",
    buttonText: "repo",
  },
  {
    id: 10,
    title: "campus-api",
    description: "campus-api",
    technologies: ["Express.js", "API"],
    category: "dev",
    link: "https://github.com/pablo-crotti/on-the-way",
    buttonText: "repo",
  },
  {
    id: 11,
    title: "campus",
    description: "campus",
    technologies: ["Angular", "HTML", "CSS", "API"],
    category: "dev",
    link: "https://github.com/pablo-crotti/on-the-way",
    buttonText: "repo",
  },
  {
    id: 12,
    title: "oep",
    description: "oep",
    technologies: ["Laravel", "Vue.js", "API"],
    category: "fullstack",
    link: "https://github.com/pablo-crotti/on-en-parle",
    buttonText: "repo",
  },
];
