export const SKILLS = [
  {
    name: "Vue.js",
    level: 90,
    category: "dev",
    color: "from-green-500 to-emerald-500",
  },
  {
    name: "Next.js",
    level: 86,
    category: "dev",
    color: "from-purple-400 to-pink-500",
  },
  {
    name: "PHP",
    level: 85,
    category: "dev",
    color: "from-blue-500 to-indigo-500",
  },
  {
    name: "Laravel",
    level: 88,
    category: "dev",
    color: "from-red-500 to-orange-500",
  },
  {
    name: "JavaScript",
    level: 92,
    category: "dev",
    color: "from-yellow-500 to-amber-500",
  },
  {
    name: "HTML/CSS",
    level: 95,
    category: "dev",
    color: "from-orange-500 to-red-500",
  },
  {
    name: "React",
    level: 88,
    category: "dev",
    color: "from-sky-500 to-blue-500",
  },
  {
    name: "Angular",
    level: 80,
    category: "dev",
    color: "from-red-600 to-pink-500",
  },
  {
    name: "Tailwind CSS",
    level: 90,
    category: "dev",
    color: "from-teal-400 to-cyan-500",
  },
  {
    name: "Figma",
    level: 90,
    category: "design",
    color: "from-purple-500 to-violet-500",
  },
  {
    name: "Illustrator",
    level: 85,
    category: "design",
    color: "from-pink-500 to-rose-500",
  },
  {
    name: "UX Design",
    level: 88,
    category: "design",
    color: "from-cyan-500 to-blue-500",
  },
  {
    name: "UI Design",
    level: 87,
    category: "design",
    color: "from-teal-500 to-green-500",
  },
  {
    name: "Canva",
    level: 80,
    category: "design",
    color: "from-indigo-400 to-purple-400",
  },
  {
    name: "Premiere Pro",
    level: 78,
    category: "design",
    color: "from-indigo-500 to-pink-500",
  },
  {
    name: "API REST",
    level: 85,
    category: "fullstack",
    color: "from-violet-500 to-purple-500",
  },
  {
    name: "Bases de données",
    level: 82,
    category: "fullstack",
    color: "from-indigo-500 to-blue-500",
  },
  {
    name: "Git",
    level: 90,
    category: "fullstack",
    color: "from-gray-500 to-slate-500",
  },
];
